In [1]:
import numpy as np
import pandas as pd
# random.normal gets random sample from normal distribution.
df = pd.DataFrame(np.random.normal(size=(6,6)), columns = [x for x in 'ABCDEF'])

In [2]:
df.head()

          A         B         C         D         E         F
0 -0.337043  1.460813 -0.824353  0.241167 -1.418449 -1.753769
1  0.724967  0.704016 -0.545639  2.416852 -1.578315 -0.341183
2  0.577144  0.489773 -0.960687 -1.283186  1.107053  1.155036
3  0.382333 -0.264701  0.255721 -1.261652 -0.010930  0.003449
4  0.884278 -1.558015  0.186906 -0.344182  0.911062  1.463061

In [5]:
def neg_red(x):
    return f"color: {'red' if x < 0  else 'white'}"
df.style.applymap(neg_red)

In [9]:
def gold_max(xs):
    m = xs.to_numpy().max()
    color = {True: "background-color: #c78f2e", False:""}
    is_max = (xs==m).replace(color)
    return is_max
df.style.apply(gold_max,axis=0)

In [10]:
df.style.background_gradient(cmap='magma')

In [13]:
df.abs().style.bar(align='left',width=80)